%{
# Template for the information of each column
template_name        :    varchar(64)         # field name, such as 'Cage ID'
---
original_field_names :    longblob            # cell array for original field names
database_field_names :    longblob            # cell array for database field names
%}

classdef Template < dj.Lookup
    properties
        contents = [
            {'Animal', ...
             {'field', 'description', 'grouping', 'identifier', 'data', 'futurePlans', 'mandatory', 'isFilter'}, ...
             {'field', 'description', 'grouping', 'identifier', 'data', 'future_plans', 'mandatory', 'is_filter'}}; ...  
            {'DailyInfo', ...
             {'field', 'description', 'grouping', 'identifier', 'data', 'mandatory', 'isDynamic', 'isFilter', 'isTrials'}, ...
             {'field', 'description', 'grouping', 'identifier', 'data', 'mandatory', 'is_dynamic', 'is_filter', 'is_trials'}}; ...  
            {'RightNow', {'data'}, {'data'}}; ...
            {'ActionItems', {'value'}, {'value'}}; ...
            {'Genotype', {'value'}, {'value'}}
        ]
    end
end
